src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\Column(type: 'text')]
    private $content;

    #[ORM\Column(type: 'datetime')]
    private $CreateAt;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $image;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->CreateAt;
    }

    public function setCreateAt(\DateTimeInterface $CreateAt): self
    {
        $this->CreateAt = $CreateAt;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }


}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleFormType;
use App\Repository\ArticleRepository;
use App\Service\FileUploader;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ObjectManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BlogController extends AbstractController
{

    /**
     * @Route("/", name="home")
     */

    public function index() : Response{

        return $this->render('blog/index.html.twig'
        );
    }

    /**
     * @Route("/articles", name="articles")
     */

    public function liste_articles(ArticleRepository $repo){
        $articles = $repo->findAll();

        return $this->render('blog/articles.html.twig', [
            'articles' => $articles,
        ]);
    }

    /**
     * @Route("/article/new", name="addArticle")
     * @Route("/article/edit/{id}", name= "article_edit")
     *
     */
    public function formArticle(Article $article = null, Request $request, EntityManagerInterface $manager,
                                FileUploader $fileUploader){

        date_default_timezone_set('Europe/Paris');
        if (!$article) {
            $article = new Article();
            $article->setCreateAt(new \DateTime());
        }

        $form = $this->createForm(ArticleFormType::class, $article);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $article = $form->getData();

            $articleFile = $form->get('image')->getData();
            if ($articleFile) {
                $articleFileName = $fileUploader->upload($articleFile);
                $article->setImage($articleFileName);
            }

            $manager->persist($article);
            $manager->flush();

            return $this->redirectToRoute('articles');
        }
        return $this->renderForm('blog/addArticle.html.twig',[
            'form' => $form,
        ]);

    }

    /**
     * @Route("/article/{id}", name="anArticle")
     */
    public function anArticle($id, ArticleRepository $repo){
        $article = $repo->find($id);
        return $this->render('blog/anArticle.html.twig', [
            'article' => $article,
        ]);
    }

    /**
     * @Route("/article/remove/{id}", name="article_delete")
     */
    public function remove_article(Article $article, EntityManagerInterface $entityManager) {
        $entityManager->remove($article);
        $entityManager->flush();

        return $this->redirectToRoute('articles');
    }

}

templates/blog/addArticle.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_5_layout.html.twig' %}
{% block head %}
    <title>{% block title %}Création d'un article{%endblock%}</title>
{% endblock %}
{% block body %}
    {{ form_start(form) }}
    {{ form_row(form.title, {'label': 'Titre :'})}}
    {{ form_row(form.content, {'label': 'Contenue :'})}}
    {{ form_row(form.image, {'label': 'Image :' } )}}
    {{ form_row(form.save, {'label': 'Ajouter l\'article' })}}
    {{ form_end(form) }}
{% endblock %}

templates/blog/anArticle.html.twig
{% extends 'base.html.twig' %}
{% block head %}
    <title>{% block title %} {{article.title}} {%endblock%}</title>
{% endblock %}
{% block body %}
<h3 class="mb-0">{{article.title}}</h3>
<div class="mb-1 text-muted">{{ article.createAt | format_datetime(locale='fr') }}</div>
<p class="card-text mb-auto">{{article.content}}</p>
    {% if is_granted('ROLE_EDITOR') or is_granted('ROLE_ADMIN') %}
        <a href="{{path('article_edit', {'id' : article.id})}}" class="btn btn-primary">Modifier l'article</a>
    {% endif %}
    {% if is_granted('ROLE_ADMIN') %}
        <a href="{{path('article_delete', {'id' : article.id})}}" class="btn btn-primary">Supprimer l'article</a>
    {% endif %}
{% endblock %}

templates/blog/articles.html.twig
{% extends 'base.html.twig' %}
{% block head %}
    <title>{% block title %}Liste Articles{%endblock%}</title>
{% endblock %}
{% block body %}
    <div class="container">
        <div class="row mb-2">
        {% for article in articles %}
            <div class="col-md-6">
                <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    <div class="col p-4 d-flex flex-column position-static">
                        <h3 class="mb-0">{{article.title}}</h3>
                        <div class="mb-1 text-muted">{{ article.createAt | date("m/Y") }}</div>
                        <p class="card-text mb-auto">{{article.content}}</p>
                        <a href="{{path('anArticle', {'id' : article.id})}}" class="btn btn-primary">Voir l'article</a>
                    </div>
                    <div class="col-auto d-none d-lg-block">
                        {% if article.image != "" %}
                            <img src="{{ asset('uploads/images/' ~ article.image) }}" width="200px" height="250px">
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
{% endblock %}

templates/blog/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block body %}

<div class="example-wrapper">
    <h1 style="text-align: center">Bienvenue sur mon blog</h1>
</div>
{% endblock %}